In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
# Path to the Excel file
file_path = 'MER_LMP_Information.xlsx'
LMP_df = pd.read_excel(file_path, sheet_name = "LMP", nrows=5, usecols="A:AK")
MER_df = pd.read_excel(file_path, sheet_name = "MER", nrows=5, usecols="A:AK")
LMP_NP = LMP_df.to_numpy().T
MER_NP = MER_df.to_numpy().T
# LMP_NP = LMP_NP[1:]/1000
# MER_NP = MER_NP[1:]/1000
LMP = LMP_NP[1:]
MER_mile = MER_NP[1:]
LMP = LMP.astype(float)
# MER_mile = MER_mile.astype(float)
# LMP = np.round(LMP, decimals=0)
print(LMP)
print('Note: This is in $/MWh')

[[25.52603376 13.04592915 13.34816313 13.39805572 13.38510284]
 [23.57451391 12.63610475 12.90100309 12.94473234 12.93337955]
 [24.2669     12.87416164 13.15006258 13.19560813 13.18378381]
 [25.99377633 13.2365654  13.54551014 13.59651054 13.58327005]
 [21.14078769 12.07869164 12.29815081 12.33437899 12.3249736 ]
 [23.74995718 12.77357887 13.03939672 13.08327776 13.07188557]
 [18.90773589 11.87626464 12.01904523 12.04261536 12.03649619]
 [19.05273033 11.50270828 11.66252578 11.68890835 11.68205903]
 [21.09589471  8.58314308  8.83414483  8.87558004  8.86482282]
 [21.09049576  8.57991733  8.82756695  8.8684488   8.85783524]
 [22.41802236 12.41214341 12.62982477 12.66575947 12.65643027]
 [21.98656107 12.35026203 12.58362682 12.62215053 12.61214918]
 [21.02925049  8.31770464  8.58444153  8.62847428  8.6170427 ]
 [20.20098111  8.05736549  8.30696886  8.34817322  8.33747594]
 [20.21136698  7.89394907  8.12298235  8.16079102  8.15097531]
 [20.19056079  7.48043915  7.67880431  7.71155031  7.70

In [ ]:
# plot

In [8]:
# generate the lp file
vertiport = ["lbm", "mgt", "tci", "mbf", "crj"]
with open('mer_lmp.lp', 'w') as file:
    for v in vertiport:
        for t in range(0, 36):
            index_v = vertiport.index(v)
            file.write(f'lmp({int(LMP[t][index_v])}, {v}, {str((t+1)*10)}).\n')
