In [15]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
# Path to the Excel file
file_path = 'MER_LMP_Information.xlsx'
LMP_df = pd.read_excel(file_path, sheet_name = "LMP", nrows=7, usecols="A:S")
MER_df = pd.read_excel(file_path, sheet_name = "MER", nrows=7, usecols="A:S")
LMP_NP = LMP_df.to_numpy().T
MER_NP = MER_df.to_numpy().T
# LMP_NP = LMP_NP[1:]/1000
# MER_NP = MER_NP[1:]/1000
LMP_mile = LMP_NP[1:]/4
MER_mile = MER_NP[1:]/4
LMP_mile = LMP_mile.astype(float)
MER_mile = MER_mile.astype(float)
LMP_mile = np.round(LMP_mile, decimals=0)
print(LMP_mile)
print('Note: This is in $/MWh')

[[6. 3. 3. 3. 3. 3. 3.]
 [6. 3. 3. 3. 3. 3. 3.]
 [6. 3. 3. 3. 3. 3. 3.]
 [6. 3. 3. 3. 3. 3. 3.]
 [5. 3. 3. 3. 3. 3. 3.]
 [6. 3. 3. 3. 3. 3. 3.]
 [5. 3. 3. 3. 3. 3. 3.]
 [5. 3. 3. 3. 3. 3. 3.]
 [5. 2. 2. 2. 2. 2. 2.]
 [5. 2. 2. 2. 2. 2. 2.]
 [6. 3. 3. 3. 3. 3. 3.]
 [5. 3. 3. 3. 3. 3. 3.]
 [5. 2. 2. 2. 2. 2. 2.]
 [5. 2. 2. 2. 2. 2. 2.]
 [5. 2. 2. 2. 2. 2. 2.]
 [5. 2. 2. 2. 2. 2. 2.]
 [5. 2. 2. 2. 2. 2. 2.]
 [5. 1. 2. 2. 2. 1. 2.]]


In [ ]:
# plot

In [19]:
# generate the lp file
vertiport = ["jfk", "lga", "teb", "ryend", "cri", "cimbl", "dandy"]
with open('mer_lmp_mile.lp', 'w') as file:
    for v in vertiport:
        for t in range(0, 18):
            index_v = vertiport.index(v)
            file.write(f'lmp_mile({int(LMP_mile[t][index_v])}, {v}, {str((t+1)*10)}).\n')
